#!/usr/bin/python2
from utilities.utilities import mkdir_p

import json, os, subprocess

"""
This is a utility script useful for copying analysis files generated by automated analyses from config location to experiment data location
"""

def main():
    """
    Main script
    """
    settings_fn = "param/stepping_stones_analysis_settings.json"
    settings = None
    # Load settings from settings file
    with open(settings_fn) as fp:
        settings = json.load(fp)
    # Pull out general locations of interest
    experiment_loc = settings["experiment_data"]["base_location"]
    treats_configs_loc = settings["avida_analysis_config"]["config_loc"]
    # Pull out some other settings
    treats_to_cp = settings["avida_analysis_config"]["treatments_to_analyze"]

    for treatment in treats_to_cp:
        print "Copying %s " % treatment
        treat_analyses_src = os.path.join(treats_configs_loc, treatment, "configs", "data", "analysis")
        treat_analyses_dest = os.path.join("test", treatment)
        cmd = "cp -r %s %s" treat_analyses_src treat_analyses_dest
        return_code = subprocess.call(cmd, shell = True)

if __name__ == "__main__":
    main()
